// Database 
const SUCCESS = 'SUCCESS';
const FAIL= 'FAIL';

module.exports = Object.freeze({
	// Commom Error codes
	SUCCESS: SUCCESS,
	FAIL: FAIL,
	MISSING_MANDATORY_ATTRIBUTE: 'MISSING_MANDATORY_ATTRIBUTE',
	RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
	NOT_FOUND: 'NOT_FOUND',
	EXCEED_CHARACTER_LENGTH: 'EXCEED_CHARACTER_LENGTH',
	INVALID_DATA: 'INVALID_DATA',
});